tune thp to defer  in csi-node init-container (#177)
* Add support for transparent hugepage tuning in csi-node

Signed-off-by: Zzde <zhangxh1997@gmail.com>

* use csi-driver image

Signed-off-by: Zzde <zhangxh1997@gmail.com>

* bump to 0.28.3

Signed-off-by: Zzde <zhangxh1997@gmail.com>

---------

Signed-off-by: Zzde <zhangxh1997@gmail.com>

diff --git a/charts/juicefs-csi-driver/templates/daemonset.yaml b/charts/juicefs-csi-driver/templates/daemonset.yaml
--- a/charts/juicefs-csi-driver/templates/daemonset.yaml
+++ b/charts/juicefs-csi-driver/templates/daemonset.yaml
@@ -44,6 +44,29 @@ spec:
       hostAliases:
       {{- toYaml .Values.hostAliases | nindent 6 }}
     {{- end }}
+  {{- if .Values.node.tuneTransparentHugePage }}
+      initContainers:
+      - name: setup-thp
+        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
+        {{- if .Values.image.pullPolicy }}
+        imagePullPolicy: {{ .Values.image.pullPolicy }}
+        {{- end }}
+        command:
+        - /bin/sh
+        - -c
+        - |
+          if [ -f /host-sys/kernel/mm/transparent_hugepage/defrag ]; then
+            echo "Setting transparent hugepage defrag to defer"
+            echo defer > /host-sys/kernel/mm/transparent_hugepage/defrag 2>/dev/null || echo "Failed to set THP defrag"
+          else
+            echo "Transparent hugepage defrag file not found, skipping"
+          fi
+        securityContext:
+          privileged: true
+        volumeMounts:
+        - name: host-sys
+          mountPath: /host-sys
+  {{- end }}
       containers:
       - name: juicefs-plugin
         image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
@@ -274,5 +297,11 @@ spec:
       - name: juicefs-config
         configMap:
           name: {{ include "juicefs-csi.fullname" . }}-config
+      {{- end }}
+      {{- if .Values.node.tuneTransparentHugePage }}
+      - hostPath:
+          path: /sys
+          type: Directory
+        name: host-sys
       {{- end }}
 {{- end }}
